linters-settings:
  funlen:
    lines: 100
    statements: 80
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/tiendc/go-deepcopy)
  gocyclo:
    min-complexity: 20
  goimports:
    local-prefixes: github.com/golangci/golangci-lint
  gomnd:
    settings:
      mnd:
        checks: # don't include the "operation" and "assign"
          - argument
          - case
          - condition
          - return
  lll:
    line-length: 120
  misspell:
    locale: US

linters:
  enable:
    - bodyclose
    - contextcheck
    - dogsled
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - forbidigo
    - forcetypeassert
    - funlen
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - goerr113
    - gofmt
    - goimports
    - gomnd
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nestif
    - nilerr
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - contextcheck
        - staticcheck
        - gocyclo
        - gocognit
        - goerr113
        - forcetypeassert
        - wrapcheck
        - gomnd
        - errorlint
        - unused

run:
  skip-dirs:
    - scripts
    - test-results

# golangci configuration
# https://github.com/golangci/golangci/wiki/Configuration
service:
  golangci-lint-version: 1.50.x
